os:
  - linux
  - osx


language: python
python:
  - "3.8"
  - "pypy3"

install:
  - pip install -r requirements.txt
  - git clone https://github.com/jean-emmanuel/open-stage-control --depth 1
  - cd open-stage-control/src/python/
  - pyinstaller midi.py --onefile
