matrix:
  include:
  - os: linux
    language: python
    python: 3.7
  - os: osx
    language: minimal
    before_install:
      - brew install python
      - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
      - python get-pip.py
  - os: windows
    language: minimal
    before_install:
      - choco install python --version=3.7
      - python -m pip install --upgrade pip
      - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"

install:
  - pip install -r requirements.txt
  - git clone https://github.com/jean-emmanuel/open-stage-control --depth 1
  - cd open-stage-control/src/python/
  - pyinstaller midi.py --onefile

deploy:
  provider: releases
  api-key:
    secure: Nb4qJlmLEE2/ETHEYe8V8eGI08d4GuE5kdQef5ZnB4PrstppLlAjShv5E4DNTsyalMOMDjpw9v+9aQNzxGiGv+lCVVL5oFvqvDpcYusRuF9Qua7oJtFh+5FvjgC1DDjauk5Z7WQWMvzWwfNmqbY/lxPbA4zVy4kdYkGV/8WnzA9AL5fU0ZU8gDsFjcr9Pz81XDsDXtPH/+iMuclMsEl8V/ZuswWlZaFn1Jnb1tcGC5WUCsuNQo/+gGfSK6Qcf9AKsIrOjdzi55s4jqH1N7P/kKi4a2tWUTwmSLrOxdUmSYjXVOxMu0cAEnHSeYREv/5o6J0MbfQrDoxh2y5roPZzqE+FAuFLl+b/+bYlW0mrfYfSuP/VX9LYh5JSvrhN7rZuUfMqS1iM7c9Dx8sZadMnvYEAAJhH8IV/9SkuRa/8QoIpXf7YB9v1jERxs4gk5CPT5Aml6nY/CvMWiEQ/wJhC7iZd/QRHshgfNLfAGlbbNU2KP6ZsVAGD601fyST/8neoQqLqS9mteOr1QME3c5EFw+XaauIQNYZSl+wJr8Y1YMcKY+fbJqqR0TXkbsoxFgV9PRf/4ZCjIJYtmelQVlM7j20XavOHM/Ko6/y7a3pohFz+ql3YR9jGF5XW2foXb4+e6DwTGL91/f75hYcsvXxoKbeaBjWpaSK8532UTeVkhPM=
  file_glob: true
  file: open-stage-control/src/python/dist/*
  skip_cleanup: true
  on:
    tags: true
